### PR TITLE
[JENKINS-66308] Prepare SonarQube Scanner for core Guava upgrade

### PR DESCRIPTION
**Pull request by basil**
The portions of #201 required for the Jenkins core Guava update and the minimum necessary build metadata updates to support it.

### CODE REVIEW

**Comment by timja** [comment]
@wouter-admiraal-sonarsource would we be able to get a release of this please?

**Comment by wouter-admiraal-sonarsource** [comment]
@henryju I believe you're the only one that has the rights to perform a release, is that still correct? (if so, we should do something about this, BTW)

**Comment by timja** [comment]
@wouter-admiraal-sonarsource just send a PR here https://github.com/jenkins-infra/repository-permissions-updater/blob/master/permissions/plugin-sonar.yml

With your Jenkins Jira account

**Comment by timja** [comment]
@wouter-admiraal-sonarsource reminder about a release

cc @jacek-poreda-sonarsource @lukasz-jarocki-sonarsource

**Comment by timja** [comment]
@wouter-admiraal-sonarsource  @henryju @malena-ebert-sonarsource  @lukasz-jarocki-sonarsource @dbmeneses 

Could we please get a release?
Jenkins will be incompatible with this plugin from the next release on Tuesday 9th November.

**Comment by wouter-admiraal-sonarsource** [comment]
Hey. Sorry for this delay, we've been extremely busy. I'm going to bring this up at our team planning upcoming Monday, so we can schedule a release for next week.

**Comment by wouter-admiraal-sonarsource** [comment]
@timja 

> @wouter-admiraal-sonarsource just send a PR here https://github.com/jenkins-infra/repository-permissions-updater/blob/master/permissions/plugin-sonar.yml
> 
> With your Jenkins Jira account

I've opened a PR here: https://github.com/jenkins-infra/repository-permissions-updater/pull/2161

**Pull request merged**
