### PR TITLE
update(ci): add dependabot config for dependency patching

### PR DESCRIPTION
**Pull request by h1dden-da3m0n**
**Description**

Based on my other PR I noticed that this repo has no [Dependabot](https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/enabling-and-disabling-version-updates#enabling-dependabot-version-updates) config.
In case you want to use it I open this PR to add such a config to scan weekly for dependency updates and open at most 10 PRs at the same time.

Up to you if you find this useful :wink: 

**Changes**

* add dependabot v2 config

**Issues**

* N/A

### CODE REVIEW

**Comment by mark-rekveld-sonarsource** [comment]
Hi,

Thanks for the PR submission.
We already use a dependabot so not sure if we need this configuration, but will checkin internally to see if the person that enabled the existing dependabot knows.

Cheers,
Mark

**Comment by h1dden-da3m0n** [comment]
Given your CI build structure, based on your comment from my other PR, I think this my not work as I intended anyway.
However thank you for evaluating :wink:

**Comment by mark-rekveld-sonarsource** [comment]
Ok I have spoken with someone internally that handles the build infrastructure and we currently only use the dependabot for security vulnerability updates.
So thanks for your contribution but at this time we won't be enabling the dependabot for all version updates

**Comment by h1dden-da3m0n** [comment]
No worries, I kind of expected this :wink:  Thank you for your work with this plugin and SonarQube in general :+1:

**Pull request closed without merging**
