### PR TITLE
SONARJNKNS-312 Make triggers optional for configuration via CasC

### PR DESCRIPTION
**Pull request by wouter-admiraal-sonarsource**
Internal PR for #136

### CODE REVIEW

**Comment by wouter-admiraal-sonarsource** [comment]
> Ideally we would have a test that checks if providing the 'triggers' configuration still works.
But checked it manually and it works as expected.

I have no experience with this, so won't be of much use here. @Smasherr Do you mind adding a test case?

**Comment by Smasherr** [comment]
> @Smasherr Do you mind adding a test case?

Sure that will be easy, I'll do that.

**Comment by Hokwang** [comment]
How's this going??

**Comment by Smasherr** [comment]
I added the required test case to #136 and wait for it to be merged in this PR...

**Comment by wouter-admiraal-sonarsource** [comment]
Sorry for the delay. Rebased, and waiting for QA to pass.

**Comment by timja** [comment]
Could we get a release please?

**Comment by Smasherr** [comment]
@wouter-admiraal-sonarsource @henryju @tom-vanbraband-sonarsource
We all are still wating for a release

**Comment by Hokwang** [comment]
I am waiting too.

**Pull request merged**
